import { createClient } from '../../utils/supabase/client';

const STORAGE_KEY = 'invoice_profile';
const supabase = createClient();

const defaultProfile = {
    name: '',
    address: '',
    ico: '',
    dic: '',
    phone: '',
    email: '',
    note: '',
    account: '',
    iban: '',
    swift: '',
    method: '',
    logo: '',
    accentColor: '#875FDC',
    secondaryColor: '#181020',
    backgroundColor: '#F7F3FF',
    primaryTextColor: '#181020',
    footerTextColor: '#F7F3FF',
    fontFamily: 'Saira',
    insuranceSettings: {}
};

const ProfileService = {
    fetchProfile: async () => {
        try {
            // Profil míváme uložen zpravidla jen v jedné řádce pro danou instanci (např AuthID)
            // Pro teď vezmeme první nalezený, jelikož se neregistrujeme
            const { data, error } = await supabase
                .from('profile')
                .select('*')
                .limit(1);

            if (error) throw error;

            if (data && data.length > 0) {
                const dbProf = data[0];
                // Mapováni hadích názvů ze Supabase na React CamelCase JSON
                const mapped = {
                    id: dbProf.id,
                    name: dbProf.name || '',
                    address: dbProf.address || '',
                    ico: dbProf.ico || '',
                    dic: dbProf.dic || '',
                    phone: dbProf.phone || '',
                    email: dbProf.email || '',
                    note: dbProf.note || '',
                    account: dbProf.account || '',
                    iban: dbProf.iban || '',
                    swift: dbProf.swift || '',
                    method: dbProf.method || '',
                    logo: dbProf.logo || '',
                    accentColor: dbProf.accent_color,
                    secondaryColor: dbProf.secondary_color,
                    backgroundColor: dbProf.background_color,
                    primaryTextColor: dbProf.primary_text_color,
                    footerTextColor: dbProf.footer_text_color,
                    fontFamily: dbProf.font_family,
                    insuranceSettings: dbProf.insurance_settings
                };
                localStorage.setItem(STORAGE_KEY, JSON.stringify(mapped));
                return mapped;
            }
            return ProfileService.get(); // Fallback to local default if empty DB
        } catch (error) {
            console.error('Supabase profile get err:', error)
            return ProfileService.get();
        }
    },

    get: () => {
        try {
            const stored = localStorage.getItem(STORAGE_KEY);
            if (!stored) {
                localStorage.setItem(STORAGE_KEY, JSON.stringify(defaultProfile));
                return defaultProfile;
            }
            return { ...defaultProfile, ...JSON.parse(stored) };
        } catch (error) {
            console.error('Error loading profile:', error);
            return defaultProfile;
        }
    },

    save: async (profile) => {
        try {
            // Check logo size mapping (V Supabase pak ideálně napojíme na Storage bucket, ale teď v JSONB textu)
            if (profile.logo && profile.logo.length > 2000000) {
                alert('Logo je příliš velké. Doporučeno pod 2MB pro bezpečné cloud uložení.');
            }

            const dbRow = {
                name: profile.name,
                address: profile.address,
                ico: profile.ico,
                dic: profile.dic,
                phone: profile.phone,
                email: profile.email,
                note: profile.note,
                account: profile.account,
                iban: profile.iban,
                swift: profile.swift,
                method: profile.method,
                logo: profile.logo,
                accent_color: profile.accentColor,
                secondary_color: profile.secondaryColor,
                background_color: profile.backgroundColor,
                primary_text_color: profile.primaryTextColor,
                footer_text_color: profile.footerTextColor,
                font_family: profile.fontFamily,
                insurance_settings: profile.insuranceSettings
            };

            const existingStore = ProfileService.get();

            // Pokud db id již existuje, aktualizujeme jej, jinak vložíme novou.
            if (existingStore.id) {
                dbRow.id = existingStore.id;
                const { error } = await supabase.from('profile').upsert(dbRow);
                if (error) throw error;
            } else {
                const { data, error } = await supabase.from('profile').insert(dbRow).select();
                if (error) throw error;
                if (data) dbRow.id = data[0].id; // Assign ID generated by Supabase defaults
            }

            // Restore updated item
            const finalProfile = { ...profile, id: dbRow.id };
            localStorage.setItem(STORAGE_KEY, JSON.stringify(finalProfile));
            return finalProfile;

        } catch (error) {
            console.error('Error profile save:', error);
            alert('Chyba cloud synchronizace profilu.');
            return profile;
        }
    }
};

export default ProfileService;
